### ISSUE TITLE
[STORY] - Create Order Tracker

### ISSUE THREAD

**Issue by LaurieAnderson92** [LaurieAnderson92/CraftingCovern#7]
## Description
As a customer,
I want to track the shipping of my order,
so I know when to expect my items.

## Acceptance Criteria
- [ ] Orders include tracking numbers upon shipment.
- [ ] Customers can view order status in their account.
- [ ] Notifications are sent for shipping and delivery updates.
